In [67]:
import pandas as pd

df = pd.read_csv("pokemon_data.csv")
df.head()

,id,name,base_experience,height,weight,types,abilities,moves,stats
0,1,bulbasaur,64,7,69,"grass, poison","overgrow, chlorophyll","razor-wind, swords-dance, cut, bind, vine-whip","hp=45, attack=49, defense=49, special-attack=6..."
1,2,ivysaur,142,10,130,"grass, poison","overgrow, chlorophyll","swords-dance, cut, bind, vine-whip, headbutt","hp=60, attack=62, defense=63, special-attack=8..."
2,3,venusaur,236,20,1000,"grass, poison","overgrow, chlorophyll","swords-dance, cut, bind, vine-whip, headbutt","hp=80, attack=82, defense=83, special-attack=1..."
3,4,charmander,62,6,85,fire,"blaze, solar-power","mega-punch, fire-punch, thunder-punch, scratch...","hp=39, attack=52, defense=43, special-attack=6..."
4,5,charmeleon,142,11,190,fire,"blaze, solar-power","mega-punch, fire-punch, thunder-punch, scratch...","hp=58, attack=64, defense=58, special-attack=8..."

In [69]:
stats_split = df['stats'].str.extract(
    r"hp=(\\d+), attack=(\\d+), defense=(\\d+), special-attack=(\\d+), special-defense=(\\d+), speed=(\\d+)"
)
stats_split.columns = ['hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed']
stats_split = stats_split.astype(float)
df_clean = pd.concat([df, stats_split], axis=1)

In [65]:
numerical_data = df_clean[['base_experience', 'height', 'weight', 'hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed']]
print(numerical_data.describe())

       base_experience       height        weight   hp  attack  defense  \
count      1302.000000  1302.000000   1302.000000  0.0     0.0      0.0
mean        161.943932    20.467742    980.863287  NaN     NaN      NaN
std          82.532554    54.180316   1972.645170  NaN     NaN      NaN
min          36.000000     1.000000      0.000000  NaN     NaN      NaN
25%          71.000000     5.000000     89.250000  NaN     NaN      NaN
50%         165.000000    10.000000    315.500000  NaN     NaN      NaN
75%         222.500000    16.000000    818.000000  NaN     NaN      NaN
max         608.000000  1000.000000  10000.000000  NaN     NaN      NaN

       sp_attack  sp_defense  speed
count        0.0         0.0    0.0
mean         NaN         NaN    NaN
std          NaN         NaN    NaN
min          NaN         NaN    NaN
25%          NaN         NaN    NaN
50%          NaN         NaN    NaN
75%          NaN         NaN    NaN
max          NaN         NaN    NaN